apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-config-reader
  namespace: api
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-api-config-reader
  namespace: api
subjects:
  - kind: ServiceAccount
    name: api-sa
    namespace: api
roleRef:
  kind: Role
  name: api-config-reader
  apiGroup: rbac.authorization.k8s.io
