replicaCount: 2

image:
  registry: "aksstagingacr6e4ced83.azurecr.io"
  repository: "frontend"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

serviceAccount:
  create: true
